import * as T from './vendor/three.module.min.js';
import {buildScene} from './scene.js';
import {Mission,ROOMS,SPAWN,SEAT,CALL,onFloor} from './mission.js';
const $=s=>document.querySelector(s),canvas=$('#game');
const renderer=new T.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});
renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.1;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;
const scene=new T.Scene();scene.background=new T.Color('#b9bbb0');scene.fog=new T.Fog('#b9bbb0',24,65);
scene.add(new T.HemisphereLight('#f4f7ef','#72705f',1.2));const sun=new T.DirectionalLight('#fff0dc',1.4);sun.position.set(-5,2.9,3);sun.target.position.set(1,0,-2);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-11,right:11,top:13,bottom:-13,near:.1,far:30});sun.shadow.normalBias=.04;scene.add(sun,sun.target);
const world=buildScene(scene);world.colliders.push({x:7,z:4.5,w:.12,d:11});
const camera=new T.PerspectiveCamera(70,1,.045,80);camera.rotation.order='YXZ';scene.add(camera);
const mission=new Mission(),keys=new Set(),player={...SPAWN,pitch:0};let running=false,paused=false,elapsed=0,swingTime=0,toastUntil=0,action='',sound=false,audio,effects=!matchMedia('(prefers-reduced-motion: reduce)').matches;
const stick={x:0,y:0,id:null},look={id:null,x:0,y:0};let womanStep=0;
const paper=new T.Group();camera.add(paper);paper.position.set(.34,-.34,-.55);paper.rotation.z=-.35;paper.scale.setScalar(.78);
const pc=document.createElement('canvas');pc.width=256;pc.height=512;const px=pc.getContext('2d');px.fillStyle='#d8d3bd';px.fillRect(0,0,256,512);px.fillStyle='#555950';px.font='bold 28px serif';px.fillText('NEWSIS',12,55);for(let y=75;y<500;y+=12){px.fillRect(10,y,100,2);px.fillRect(125,y,110,2);}const pt=new T.CanvasTexture(pc);pt.colorSpace=T.SRGBColorSpace;
const roll=new T.Mesh(new T.CylinderGeometry(.048,.055,.64,20),new T.MeshStandardMaterial({map:pt,roughness:.9}));roll.position.y=.2;paper.add(roll);
for(const [y,r,h,color] of [[-.12,.07,.18,'#d0a78c'],[-.3,.085,.25,'#e5e7de']]){const m=new T.Mesh(new T.CylinderGeometry(r,r,h,14),new T.MeshStandardMaterial({color}));m.position.y=y;paper.add(m);}
const pellet=new T.Mesh(new T.IcosahedronGeometry(.065,1),new T.MeshStandardMaterial({color:'#ede6d1',flatShading:true}));pellet.visible=false;scene.add(pellet);
$('#shoot').onclick=()=>{mission.act('shoot');$('#choice').hidden=true;drama('PAPER SHOT','신문 한 방. 퇴근 한 판.','국장이 종이를 펼치는 사이…');tone(180,.15);};$('#obey').onclick=()=>{mission.act('obey');$('#choice').hidden=true;canvas.focus();};
const red=new T.PointLight('#ff170b',0,10);red.position.set(22.5,2.6,-27.6);scene.add(red);
function resize(){renderer.setSize(canvas.clientWidth,canvas.clientHeight,false);camera.aspect=canvas.clientWidth/canvas.clientHeight;camera.updateProjectionMatrix();}addEventListener('resize',resize);resize();
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');toastUntil=elapsed+3;}
function tone(freq=500,duration=.2){if(!sound||!audio)return;const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=freq;g.gain.setValueAtTime(.055,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+duration);}
function drama(k,t,b){$('#drama-kicker').textContent=k;$('#drama-title').textContent=t;$('#drama-body').textContent=b;$('#drama').classList.toggle('show',!!t);}
function reset(){mission.reset();Object.assign(player,SPAWN,{pitch:0});keys.clear();stick.x=stick.y=0;womanStep=0;world.woman.group.position.set(10.4,0,-4);world.boss.group.visible=false;world.boss.group.position.set(22.5,0,-26.7);$('#ending').hidden=true;$('#choice').hidden=true;pellet.visible=false;$('#cover').hidden=true;$('#hud').hidden=false;running=true;pause(false);drama('','','');toast('신문 챙겼다. 이제 엘리베이터만 잡으면 된다.');}
function pause(value){paused=value;keys.clear();stick.x=stick.y=0;$('#pause-panel').hidden=!value;if(value)document.exitPointerLock?.();else canvas.focus();}
$('#start').disabled=false;$('#start').textContent='퇴근하러 가기 →';$('#start').onclick=reset;$('#restart').onclick=reset;$('#again').onclick=reset;$('#pause').onclick=()=>pause(true);$('#resume').onclick=()=>pause(false);
$('#sound').onclick=()=>{sound=!sound;if(sound){audio??=new AudioContext();audio.resume();tone();}$('#sound').textContent=`소리 ${sound?'ON':'OFF'}`;$('#sound').setAttribute('aria-pressed',sound);};
function setEffects(){$('#effects').textContent=`화면 효과 ${effects?'ON':'OFF'}`;$('#effects').setAttribute('aria-pressed',effects);}setEffects();$('#effects').onclick=()=>{effects=!effects;setEffects();};
function swing(){if(!running||paused||swingTime>0)return;swingTime=.48;tone(140,.12);const near=[world.woman,world.coworker,world.boss].find(n=>n.group.visible&&Math.hypot(n.group.position.x-player.x,n.group.position.z-player.z)<2);if(near){near.flinch=.5;toast(near===world.boss?'국장: 신문은 읽으라고 있는 겁니다.':'앗, 신문 바람! 먼저 지나가세요.');}}
function interact(){if(!running||paused)return;if(action==='call'){mission.act('call');tone(650,.4);toast('엘리베이터를 불렀다.');}else if(action==='desk')mission.act('desk');else if(action==='board')toast('문 안쪽으로 들어가세요.');else if(action==='boardnote')toast('만든사람 안재현 · 떠든사람 최승훈, 성주현');else if(action==='talk')toast('동료: 벌써 가세요? 국장님 방금 지나가셨는데…');}
$('#interact').onclick=interact;$('#swing').onclick=swing;
addEventListener('keydown',e=>{if(!running||e.target.closest('button,a'))return;if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(e.code==='Escape'){pause(!paused);return;}keys.add(e.code);if(!e.repeat&&e.code==='KeyE')interact();if(!e.repeat&&e.code==='Space')swing();});addEventListener('keyup',e=>keys.delete(e.code));addEventListener('blur',()=>{if(running)pause(true);});
canvas.addEventListener('pointerdown',e=>{if(!running||paused)return;canvas.focus();if(e.pointerType==='mouse'){if(document.pointerLockElement!==canvas)canvas.requestPointerLock?.()?.catch?.(()=>{});return;}look.id=e.pointerId;look.x=e.clientX;look.y=e.clientY;canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointermove',e=>{if(e.pointerType==='mouse'||look.id!==e.pointerId)return;player.yaw-=(e.clientX-look.x)*.004;player.pitch=T.MathUtils.clamp(player.pitch-(e.clientY-look.y)*.003,-1.15,1.15);look.x=e.clientX;look.y=e.clientY;});for(const type of ['pointerup','pointercancel'])canvas.addEventListener(type,e=>{if(e.pointerType!=='mouse')look.id=null;});canvas.addEventListener('mousemove',e=>{if(document.pointerLockElement!==canvas||!running||paused)return;player.yaw-=e.movementX*.004;player.pitch=T.MathUtils.clamp(player.pitch-e.movementY*.003,-1.15,1.15);});
const pad=$('#stick');function moveStick(e){const r=pad.getBoundingClientRect();stick.x=T.MathUtils.clamp((e.clientX-r.left-r.width/2)/35,-1,1);stick.y=T.MathUtils.clamp((e.clientY-r.top-r.height/2)/35,-1,1);pad.firstElementChild.style.transform=`translate(${stick.x*25}px,${stick.y*25}px)`;}pad.onpointerdown=e=>{stick.id=e.pointerId;pad.setPointerCapture(e.pointerId);moveStick(e);};pad.onpointermove=e=>{if(e.pointerId===stick.id)moveStick(e);};for(const type of ['pointerup','pointercancel'])pad.addEventListener(type,()=>{stick.id=null;stick.x=stick.y=0;pad.firstElementChild.style.transform='';});
function free(x,z){if(!onFloor(x,z))return false;for(const o of world.colliders)if(Math.abs(x-o.x)<o.w/2+.23&&Math.abs(z-o.z)<o.d/2+.23)return false;if(mission.door<.8&&x>20.8&&x<24.2&&Math.abs(z+28)<.3)return false;return true;}
function move(dt){player.yaw+=((keys.has('ArrowLeft')?1:0)-(keys.has('ArrowRight')?1:0))*dt*1.8;player.pitch=T.MathUtils.clamp(player.pitch+((keys.has('ArrowUp')?1:0)-(keys.has('ArrowDown')?1:0))*dt,-1.15,1.15);let x=stick.x+(keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0),z=stick.y+(keys.has('KeyS')?1:0)-(keys.has('KeyW')?1:0);const len=Math.hypot(x,z);if(len>1){x/=len;z/=len;}const speed=(keys.has('ShiftLeft')?4:2.5)*dt;const dx=(x*Math.cos(player.yaw)+z*Math.sin(player.yaw))*speed,dz=(-x*Math.sin(player.yaw)+z*Math.cos(player.yaw))*speed;if(free(player.x+dx,player.z))player.x+=dx;if(free(player.x,player.z+dz))player.z+=dz;return len>.1;}
function updateNPC(dt){const n=world.woman,path=[[7.7,-4.6],[3,-4.6],[2,-2.5]];if(womanStep<path.length){const [x,z]=path[womanStep],dx=x-n.group.position.x,dz=z-n.group.position.z,d=Math.hypot(dx,dz);if(d<.08)womanStep++;else{n.group.position.x+=dx/d*dt*.62;n.group.position.z+=dz/d*dt*.62;n.group.rotation.y=Math.atan2(dx,dz);n.legs.forEach((l,i)=>l.rotation.x=Math.sin(elapsed*5+i*Math.PI)*.25);n.arms.forEach((l,i)=>l.rotation.x=-Math.sin(elapsed*5+i*Math.PI)*.18);}}for(const npc of [n,world.coworker,world.boss]){npc.flinch=Math.max(0,npc.flinch-dt);npc.group.rotation.z=Math.sin(npc.flinch*20)*npc.flinch*.12;}if(mission.phase==='return')world.boss.group.position.x=T.MathUtils.damp(world.boss.group.position.x,25,3,dt);}
function prompt(){const distance=p=>Math.hypot(player.x-p.x,player.z-p.z);action='';let label='';if(mission.phase==='outbound'&&distance(CALL)<2){action='call';label='엘리베이터 호출';}else if(mission.phase==='return'&&distance(SEAT)<1.6){action='desk';label='내 자리에 앉기';}else if(mission.phase==='boarding'&&player.z<-25){action='board';label='엘리베이터 안으로';}else if(distance({x:1.5,z:-5})<2){action='boardnote';label='화이트보드 읽기';}else if([world.woman,world.coworker].some(n=>distance(n.group.position)<1.8)){action='talk';label='동료와 한마디';}$('#interact').hidden=!action;$('#interact').textContent=`E · ${label}`;}
function map(){const c=$('#map').getContext('2d'),scale=4,tx=49,tz=135;c.clearRect(0,0,200,200);c.fillStyle='#102024e8';c.fillRect(0,0,200,200);c.strokeStyle='#7c958b';for(const r of ROOMS){c.fillStyle=r.id==='office'?'#55786b':'#756c59';c.fillRect(tx+r.x0*scale,tz+r.z0*scale,(r.x1-r.x0)*scale,(r.z1-r.z0)*scale);}c.fillStyle='#faeabc';c.fillRect(tx-3,tz+6*scale-3,6,6);c.fillStyle='#efad63';c.fillRect(tx+22.5*scale-3,tz-29*scale-3,6,6);c.save();c.translate(tx+player.x*scale,tz+player.z*scale);c.rotate(-player.yaw);c.fillStyle='#fff';c.beginPath();c.moveTo(0,-6);c.lineTo(-4,4);c.lineTo(4,4);c.closePath();c.fill();c.restore();c.fillStyle='#ede7d5';c.font='10px sans-serif';c.fillText('12F   편집국 → ELEVATOR',12,189);}
const games=[['puzzle','조각 사진관','assets/thumbnails/puzzle-safe-v2-360x240.jpg'],['chagok','차곡차곡','chagok/assets/thumbnail-360x240-v2.jpg'],['omok','뉴스 오목','assets/thumbnails/news-omok-safe-v2-360x240.jpg'],['mole','이슈 훔친 두더지','mole/assets/thumbnail-360x240.jpg'],['brickrunch','벽크크','brickrunch/assets/thumbnail-yodel-v2-360x240.jpg'],['minesweeper','가짜뉴스 지뢰찾기','minesweeper/assets/thumbnail-360x240.jpg'],['freecell','카드 프리셀','freecell/assets/thumbnail-card-v2-360x240.jpg'],['words','낱말수선소','assets/thumbnails/words-safe-v2-360x240.jpg'],['dododok','넌 내 도도독','dododok/assets/thumbnail-360x240.jpg'],['chungmuman','충무맨','assets/thumbnails/chungmuman-safe-v2-360x240.jpg'],['output','제목있음','assets/thumbnails/headline-safe-v2-360x240.jpg'],['tarot','충무로 타로#','assets/thumbnails/tarot-safe-v2-360x240.jpg']];
for(const [path,name,img]of games){const a=document.createElement('a');a.href=`../${path}/`;const image=document.createElement('img');image.src=`../${img}`;image.alt='';image.loading='lazy';const b=document.createElement('b');b.textContent=name;a.append(image,b);$('#games').append(a);}
let last=performance.now(),lastBeep=0;
function frame(now){requestAnimationFrame(frame);const dt=Math.min(.05,(now-last)/1000);last=now;if(running&&!paused){elapsed+=dt;const cinematic=['closing','director','choice','escape'].includes(mission.phase);const walking=cinematic?false:move(dt);if(cinematic){const delta=Math.atan2(Math.sin(Math.PI-player.yaw),Math.cos(Math.PI-player.yaw));player.yaw+=delta*Math.min(1,dt*3);player.pitch*=Math.max(0,1-dt*4);}mission.tick(dt);if(mission.phase==='boarding'&&player.z<-29&&player.x>21.3&&player.x<23.7)mission.act('board');for(const phase of mission.drain()){if(phase==='boarding'){toast('엘리베이터가 도착했다. 안으로 들어가자.');tone(830,.4);}if(phase==='closing')drama('ALMOST FREE','회사 탈출 성공…?','문이 닫힙니다.');if(phase==='director'){world.boss.group.visible=true;drama('EMERGENCY','국장이 나타났다!','사무실로 돌아가라');tone(190,.6);}if(phase==='choice'){drama('','','');$('#choice').hidden=false;$('#shoot').focus();}if(phase==='return'){drama('','','');toast('국장: 어디 가세요? 자리로 돌아갑시다.');}if(phase==='finished'||phase==='escaped'){$('#ending-title').textContent=phase==='escaped'?'회사 탈출 성공':'탈출은 실패';$('#ending-title').style.color=phase==='escaped'?'#8cd8ab':'';$('#ending-kicker').textContent=phase==='escaped'?'MISSION PASSED / OFF THE CLOCK':'MISSION FAILED / BACK TO DESK';$('#ending-body').textContent=phase==='escaped'?'종이는 국장님께. 퇴근은 나에게. 내일 일은 내일 생각하자.':'몸은 회사에 있어도, 잠깐 놀 수는 있으니까.';$('#ending').hidden=false;$('#hud').hidden=true;running=false;}}
world.leftDoor.position.x=-.72-mission.door*1.45;world.rightDoor.position.x=.72+mission.door*1.45;updateNPC(dt);pellet.visible=mission.phase==='escape'&&mission.time<.65;if(pellet.visible){pellet.position.set(22.5,1.4,-29+Math.min(1,mission.time/.65)*2.3);pellet.rotation.x+=dt*14;}if(mission.phase==='escape'){world.boss.group.rotation.x=Math.sin(Math.min(1,mission.time)*Math.PI)*.16;}const alarm=mission.phase==='director';$('#alarm').className=alarm?(effects?'on':'steady'):'';red.intensity=alarm?(effects?5+4*Math.sin(elapsed*4):3):0;if(alarm&&elapsed-lastBeep>.7){tone(Math.floor(elapsed*2)%2?650:420,.55);lastBeep=elapsed;}$('#objective').textContent=mission.phase==='return'?'사무실로 돌아가라':'회사에서 탈출하라';$('#location').textContent=([...ROOMS].reverse().find(r=>player.x>=r.x0&&player.x<=r.x1&&player.z>=r.z0&&player.z<=r.z1)?.name||'편집국')+' · 12F';$('#clock').textContent=`${String(Math.floor(mission.total/60)).padStart(2,'0')}:${String(Math.floor(mission.total%60)).padStart(2,'0')}`;prompt();map();swingTime=Math.max(0,swingTime-dt);const sw=Math.sin(swingTime/.48*Math.PI);paper.rotation.z=-.35+sw*1.4;paper.position.x=.34*Math.min(1,camera.aspect/1.25)-sw*.4;paper.position.y=-.34+(walking&&effects?Math.sin(elapsed*9)*.015:0)+sw*.13;if(elapsed>toastUntil)$('#toast').classList.remove('show');}
camera.position.set(player.x,1.67,player.z);camera.rotation.set(player.pitch,player.yaw,0);renderer.render(scene,camera);}requestAnimationFrame(frame);


