const $=selector=>document.querySelector(selector);
const board=$('#board'),loading=$('#loading'),game=$('#game'),error=$('#error'),progress=$('#progress');
let data,words=[],cells=new Map(),activeWord=null,solved=new Set();

function key(row,col){return `${row}-${col}`}
function wordCells(word){return Array.from({length:word.answer.length},(_,index)=>({row:word.row+(word.direction==='down'?index:0),col:word.col+(word.direction==='across'?index:0)}))}
function memberships(row,col){return words.filter(word=>wordCells(word).some(cell=>cell.row===row&&cell.col===col))}

function selectWord(word,focus=true){activeWord=word;document.querySelectorAll('.cell').forEach(cell=>cell.classList.remove('selected'));document.querySelectorAll('.clues button').forEach(button=>button.classList.toggle('active',Number(button.dataset.number)===word.number));wordCells(word).forEach(({row,col})=>cells.get(key(row,col))?.classList.add('selected'));if(focus){const first=wordCells(word).find(({row,col})=>!cells.get(key(row,col))?.querySelector('input').value)||wordCells(word)[0];cells.get(key(first.row,first.col))?.querySelector('input').focus()}}

function move(row,col){if(!activeWord)return;const list=wordCells(activeWord),index=list.findIndex(cell=>cell.row===row&&cell.col===col),next=list[index+1];if(next)cells.get(key(next.row,next.col))?.querySelector('input').focus()}
function checkWords(){solved.clear();words.forEach(word=>{const correct=wordCells(word).every(({row,col},index)=>cells.get(key(row,col))?.querySelector('input').value===word.answer[index]);if(correct){solved.add(word.number);wordCells(word).forEach(({row,col})=>cells.get(key(row,col))?.classList.add('correct'))}});progress.textContent=`${solved.size} / ${words.length}`;if(solved.size===words.length)finish()}

function inputCell(event,row,col){const input=event.currentTarget,value=[...input.value].pop()||'';input.value=value;if(value){move(row,col);checkWords()}}
function focusCell(row,col){const options=memberships(row,col);if(!options.length)return;if(options.length===2&&activeWord===options[0])selectWord(options[1],false);else if(!activeWord||!options.includes(activeWord))selectWord(options[0],false)}

function renderBoard(){board.style.gridTemplateColumns=`repeat(${data.cols},1fr)`;board.style.gridTemplateRows=`repeat(${data.rows},1fr)`;const numbers=new Map();words.forEach(word=>numbers.set(key(word.row,word.col),numbers.has(key(word.row,word.col))?Math.min(numbers.get(key(word.row,word.col)),word.number):word.number));for(let row=0;row<data.rows;row++)for(let col=0;col<data.cols;col++){const cell=document.createElement('div');cell.className='cell';cell.setAttribute('role','gridcell');if(memberships(row,col).length){cell.classList.add('active');const input=document.createElement('input');input.maxLength=1;input.inputMode='text';input.autocomplete='off';input.setAttribute('aria-label',`${row+1}행 ${col+1}열`);input.addEventListener('focus',()=>focusCell(row,col));input.addEventListener('input',event=>inputCell(event,row,col));input.addEventListener('keydown',event=>{if(event.key==='Backspace'&&!input.value&&activeWord){const list=wordCells(activeWord),index=list.findIndex(item=>item.row===row&&item.col===col),previous=list[index-1];if(previous){event.preventDefault();const target=cells.get(key(previous.row,previous.col)).querySelector('input');target.value='';target.focus()}}});cell.append(input);if(numbers.has(key(row,col))){const sup=document.createElement('sup');sup.textContent=numbers.get(key(row,col));cell.append(sup)}}cells.set(key(row,col),cell);board.append(cell)}}

function renderClues(){for(const direction of ['across','down']){const list=$(`#${direction}`);words.filter(word=>word.direction===direction).forEach(word=>{const item=document.createElement('li'),button=document.createElement('button');button.type='button';button.dataset.number=word.number;button.innerHTML=`<b>${word.number}</b><span>${word.clue}</span>`;button.addEventListener('click',()=>selectWord(word));item.append(button);list.append(item)})}}

function hint(){if(!activeWord)selectWord(words[0],false);const target=wordCells(activeWord).find(({row,col},index)=>cells.get(key(row,col)).querySelector('input').value!==activeWord.answer[index]);if(!target)return;const index=wordCells(activeWord).findIndex(cell=>cell.row===target.row&&cell.col===target.col),input=cells.get(key(target.row,target.col)).querySelector('input');input.value=activeWord.answer[index];input.focus();checkWords();window.gtag?.('event','crossword_hint')}
function finish(){const unique=[...new Map(words.map(word=>[word.url,word])).values()].slice(0,6);$('#articles').innerHTML=unique.map(word=>`<a href="${word.url}" target="_blank" rel="noopener"><small>${word.category} · ${word.answer}</small><b>${word.title} ↗</b></a>`).join('');$('#result').hidden=false;$('#result').scrollIntoView({behavior:'smooth'});window.gtag?.('event','crossword_complete',{words:words.length})}

async function init(){try{const response=await fetch('./data/crossword.json',{cache:'no-store'});if(!response.ok)throw new Error(response.status);data=await response.json();words=data.words;if(!Array.isArray(words)||words.length<7)throw new Error('invalid crossword');renderBoard();renderClues();progress.textContent=`0 / ${words.length}`;loading.hidden=true;game.hidden=false;selectWord(words[0],false)}catch(reason){console.error(reason);loading.hidden=true;error.hidden=false}}
$('#hint').addEventListener('click',hint);$('#check').addEventListener('click',()=>{checkWords();if(solved.size<words.length){const first=words.find(word=>!solved.has(word.number));if(first)selectWord(first);window.gtag?.('event','crossword_check',{solved:solved.size})}});init();
