(function(){'use strict';
const M=window.FootballSpace,$=id=>document.getElementById(id),ns='http://www.w3.org/2000/svg';
const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
const track=(name,params={})=>{if(typeof window.gtag==='function')window.gtag('event',name,{story:'ai_football_coach',...params});};
let lens='wing',response='follow',time=0,playing=false,frameId=null,origin=0,lastCaption='',playUntil=M.duration,wholeView=true;
const make=(tag,attrs={})=>{const node=document.createElementNS(ns,tag);Object.entries(attrs).forEach(([k,v])=>node.setAttribute(k,v));return node;};
const home=M.homeBase.map((p,i)=>{const g=make('g');g.appendChild(make('circle',{r:23,fill:'none',stroke:'#e9d29a','stroke-width':2.2,class:'marker-ring'}));g.appendChild(make('ellipse',{cy:4,rx:15,ry:14,fill:'#081d15',opacity:.3}));g.appendChild(make('circle',{r:14,fill:i===0?'#d6bd7e':'#ce706b',stroke:i===0?'#f0dfa9':'#f3c5bd','stroke-width':1.4}));g.appendChild(make('path',{d:'M-5 -10V9M5 -10V9',stroke:'#8d3c42','stroke-width':1.7,opacity:.55}));const text=make('text',{y:41,class:'marker-label'});g.appendChild(text);$('homeMarkers').appendChild(g);return {g,text};});
const away=M.awayBase.map((p,i)=>{const g=make('g');g.appendChild(make('circle',{r:21,fill:'none',stroke:'#d5e5ec','stroke-width':2,class:'opponent-ring'}));g.appendChild(make('ellipse',{cy:4,rx:14,ry:13,fill:'#081d15',opacity:.3}));g.appendChild(make('circle',{r:12,fill:i===0?'#8ba485':'#648ea4',stroke:'#b2c9d1','stroke-width':1.4}));const text=make('text',{y:-29,class:'opponent-label'});g.appendChild(text);$('awayMarkers').appendChild(g);return {g,text};});
function draw(){const s=M.sample(response,time),focus=M.lenses[lens],focusIndices=focus.indices||[],opponentLabels=focus.opponents?.[response]||{};home.forEach((e,i)=>{const selected=!wholeView&&focusIndices.includes(i);e.g.setAttribute('transform','translate('+s.home[i].join(' ')+')');e.g.classList.toggle('highlighted',selected);e.g.classList.toggle('is-muted',!wholeView&&!selected);e.text.textContent=selected?(focus.labels[i]||''):'';});away.forEach((e,i)=>{const selected=!wholeView&&Object.prototype.hasOwnProperty.call(opponentLabels,i);e.g.setAttribute('transform','translate('+s.away[i].join(' ')+')');e.g.classList.toggle('opponent-highlighted',selected);e.g.classList.toggle('is-muted',!wholeView&&!selected);e.text.textContent=selected?opponentLabels[i]:'';});
 $('football').setAttribute('cx',s.ball[0]);$('football').setAttribute('cy',s.ball[1]);$('passTrail').setAttribute('d',s.passing?'M'+s.from.join(' ')+'L'+s.ball.join(' '):'');
 $('openSpace').setAttribute('opacity',s.space);
 $('movementTrail').replaceChildren();if(!wholeView){const frames=M.clips[response],start=M.sample(response,focus.time);focusIndices.forEach((index,order)=>{const points=frames.filter(f=>f.at>=focus.time&&f.at<=s.time).map(f=>f.home[index]);points.unshift(start.home[index]);points.push(s.home[index]);if(points.length>1){$('movementTrail').appendChild(make('path',{d:'M'+points.map(p=>p.join(' ')).join('L'),'stroke-opacity':order?'.5':'.78','stroke-dasharray':order?'7 6':'none'}));}});}
 $('replayTime').value=Math.round(time);$('replayClock').textContent=(time/1000).toFixed(1)+' / 8.0초';
 if(lastCaption!==s.caption){$('playCaption').textContent=s.caption;lastCaption=s.caption;}
}
function stop(){playing=false;if(frameId!==null)cancelAnimationFrame(frameId);frameId=null;$('playReplay').textContent='▶ 8초 재생';$('playReplay').setAttribute('aria-label','전체 8초 공격 재생');}
function frame(now){time=Math.min(playUntil,Math.max(0,now-origin));draw();if(time>=playUntil){const segmentEnded=playUntil<M.duration;stop();if(segmentEnded){lastCaption='선택한 움직임 구간이 끝났습니다. 전체 8초로 연결을 확인해 보세요.';$('playCaption').textContent=lastCaption;}return;}frameId=requestAnimationFrame(frame);}
function play(limit=M.duration,restart=0){if(playing){stop();return;}playUntil=Math.min(M.duration,Math.max(restart,limit));if(time>=playUntil||time<restart)time=restart;playing=true;origin=performance.now()-time;$('playReplay').textContent='Ⅱ 멈춤';$('playReplay').setAttribute('aria-label','공격 일시 정지');frameId=requestAnimationFrame(frame);}
function updateLens(){const l=M.lenses[lens],hold=response==='hold';if(wholeView){document.querySelectorAll('[data-lens]').forEach(b=>b.setAttribute('aria-pressed','false'));$('lensKicker').textContent='전체 연결 / 8초';$('lensTitle').textContent=hold?'길이 닫히면,\n방향을 바꾼다.':'벌리고, 잇고,\n침투한다.';$('lensCopy').textContent=hold?'같은 길을 억지로 반복하지 않고 반대편에서 전개를 다시 시작합니다.':'세 움직임은 다른 전술이 아니라 한 공격을 함께 만드는 연결입니다.';return;}document.querySelectorAll('[data-lens]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.lens===lens)));$('lensKicker').textContent=l.kicker;$('lensTitle').textContent=hold?l.holdTitle:l.title;$('lensCopy').textContent=hold?l.holdCopy:l.copy;}
function updateResponse(){document.querySelectorAll('[data-response]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.response===response)));$('conditionalCopy').textContent=response==='follow'?'수비가 따라오며 안쪽 길이 열립니다.':'수비가 자리를 지켜 같은 길이 닫힙니다.';$('replayTakeaway').textContent=response==='follow'?'세 움직임이 이어져 한 번의 공격을 만듭니다.':'공간이 닫히면 반대편에서 다시 연결합니다.';}
function applySelectionMethod(detail){
 if(!detail||!detail.choice)return;
 const choice=detail.choice;
 wholeView=true;stop();time=0;updateLens();draw();
 const carry=$('tacticalCarry');if(!carry)return;
 $('tacticalCarryTitle').textContent=choice==='selected'?'면담에서 새 장점을 봤다.\n이제 움직임을 볼 차례.':choice==='watch'?'기록에서 본 강점이 더 앞섰다.\n이제 움직임을 볼 차례.':'면담에서도 답을 찾지 못했다.\n이제 팀 안의 역할을 본다.';
 $('tacticalCarryCopy').textContent=choice==='selected'?'면담에서 확인한 역할과 눈빛이 팀의 움직임으로 이어지는지 봅니다.':choice==='watch'?'최근 경기력에서 확인한 강점이 팀의 움직임으로 이어지는지 봅니다.':'한 선수의 답을 넘어, 서로 다른 강점을 어떻게 연결할지 봅니다.';
 carry.hidden=false;requestAnimationFrame(()=>carry.classList.add('is-visible'));
}
window.addEventListener('selectionMethodComplete',event=>{applySelectionMethod(event.detail);track('selection_complete',{selection_result:event.detail?.choice||'unknown'});});
document.querySelectorAll('[data-lens]').forEach(b=>b.addEventListener('click',()=>{wholeView=false;stop();lens=b.dataset.lens;track('tactic_role_select',{role:lens});const l=M.lenses[lens];time=l.time;$('tacticsControls').classList.add('has-role-choice');$('tacticsGuide').innerHTML='<b>좋아요. 이제 수비 반응을 눌러보세요.</b><span>같은 움직임이 수비 선택에 따라 달라집니다.</span>';updateLens();draw();if(!reduced)play(l.end,l.time);}));
document.querySelectorAll('[data-response]').forEach(b=>b.addEventListener('click',()=>{const focused=!wholeView,l=M.lenses[lens];stop();response=b.dataset.response;track('tactic_defense_select',{defense_response:response,role:lens});time=focused?l.time:1100;$('tacticsControls').classList.add('has-response-choice');$('tacticsGuide').innerHTML='<b>선택 완료. 버튼을 바꿔가며 비교해보세요.</b><span>움직임과 수비 반응의 조합마다 장면이 달라집니다.</span>';updateResponse();updateLens();draw();if(!reduced)play(focused?l.end:M.duration,time);}));
$('playReplay').addEventListener('click',()=>{if(playing){stop();return;}track('tactic_replay_start');wholeView=true;time=0;updateLens();draw();play(M.duration,0);});$('resetReplay').addEventListener('click',()=>{wholeView=true;stop();time=0;updateLens();draw();});$('replayTime').addEventListener('input',e=>{stop();time=Math.max(0,Math.min(M.duration,Number(e.target.value)||0));draw();});
const matchSchedule={
 sep:{title:'9월 일정',count:'2경기 · 모두 오후 8시',fixtures:[['2026-09-24T20:00:00+09:00','09.24','목','에콰도르','수원월드컵경기장'],['2026-09-28T20:00:00+09:00','09.28','월','우루과이','서울월드컵경기장']]},
 oct:{title:'10월 일정',count:'2경기 · 모두 오후 8시',fixtures:[['2026-10-02T20:00:00+09:00','10.02','금','베네수엘라','울산문수축구장'],['2026-10-06T20:00:00+09:00','10.06','화','우즈베키스탄','용인미르스타디움']]},
 nov:{title:'11월 일정',count:'2경기 예정 · 상대·장소 미정',fixtures:[]}
};
const monthTabs=[...document.querySelectorAll('[data-match-month]')];
function renderMatchMonth(key){const data=matchSchedule[key],list=$('matchFixtures'),banner=$('matchBanner'),tabs=$('monthTabs'),active=monthTabs.find(tab=>tab.dataset.matchMonth===key&&tab.getAttribute('aria-selected')==='true');if(!data||!list)return;if(active&&banner&&!banner.hidden){monthTabs.forEach(tab=>{tab.setAttribute('aria-selected','false');tab.setAttribute('aria-expanded','false');});banner.hidden=true;if(tabs)tabs.classList.remove('has-selection');$('monthGuide').innerHTML='<b>월을 눌러 일정을 펼쳐보세요.</b><span>9월 · 10월 · 11월 중 하나를 선택하세요 ↓</span>';return;}$('matchMonthTitle').textContent=data.title;$('matchMonthCount').textContent=data.count;list.replaceChildren();if(!data.fixtures.length){const empty=document.createElement('li');empty.className='is-upcoming';const strong=document.createElement('strong');strong.textContent='상대·장소 미정';const note=document.createElement('span');note.textContent='11월 A매치 2경기는 예정돼 있으며 세부 일정은 아직 발표되지 않았습니다.';empty.append(strong,note);list.appendChild(empty);}else data.fixtures.forEach(item=>{const li=document.createElement('li'),timeNode=document.createElement('time'),day=document.createElement('small'),opponent=document.createElement('b'),venue=document.createElement('span');timeNode.setAttribute('datetime',item[0]);timeNode.textContent=item[1]+' ';day.textContent=item[2];timeNode.appendChild(day);opponent.textContent=item[3];venue.textContent=item[4];li.append(timeNode,opponent,venue);list.appendChild(li);});monthTabs.forEach(tab=>{const isActive=tab.dataset.matchMonth===key;tab.setAttribute('aria-selected',String(isActive));tab.setAttribute('aria-expanded',String(isActive));});if(tabs)tabs.classList.add('has-selection');$('monthGuide').innerHTML='<b>'+data.title+'을 열었습니다.</b><span>같은 달을 다시 누르면 접힙니다.</span>';if(banner){banner.hidden=false;banner.classList.remove('is-refreshing');void banner.offsetWidth;banner.classList.add('is-refreshing');}}
monthTabs.forEach(tab=>tab.addEventListener('click',()=>{track('schedule_month_toggle',{month:tab.dataset.matchMonth});renderMatchMonth(tab.dataset.matchMonth);}));
document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();});
if('IntersectionObserver' in window){const visibility=new IntersectionObserver(entries=>{if(!entries[0].isIntersecting)stop();},{threshold:.05});visibility.observe($('spaceBoard'));}
const openingFrames=[...document.querySelectorAll('[data-opening-frame]')];let openingStep=-1,scrollFrame=null;
function openingProgress(){const rect=$('opening').getBoundingClientRect(),height=rect.height||rect.bottom-rect.top,travel=height-window.innerHeight,progress=travel>0?Math.max(0,Math.min(1,-rect.top/travel)):0;const step=progress<.3?0:progress<.66?1:2;
 if(openingStep!==step){openingStep=step;openingFrames.forEach((node,i)=>{node.classList.toggle('is-active',i===step);node.inert=i!==step;});$('openingStage').classList.toggle('has-photo',step>0);$('openingStage').classList.toggle('is-photo-bright',step===2);$('openingStage').style.setProperty('--scene-photo',step===0?'0':step===1?'.34':'.50');$('openingHint').textContent=step===2?'아래로 스크롤해 선택 기준 보기 ↓':'천천히 스크롤해 보세요 ↓';}}
function readingProgress(){const max=document.documentElement.scrollHeight-window.innerHeight;$('readingProgress').style.width=(max>0?Math.max(0,Math.min(100,window.scrollY/max*100)):0)+'%';openingProgress();}
function scheduleReading(){if(scrollFrame!==null)return;scrollFrame=requestAnimationFrame(()=>{scrollFrame=null;readingProgress();});}
window.addEventListener('scroll',scheduleReading,{passive:true});window.addEventListener('resize',scheduleReading);updateLens();updateResponse();draw();if(window.latestSelectionMethod)applySelectionMethod(window.latestSelectionMethod);readingProgress();document.documentElement.classList.add('story-ready');

const shareStory=$('shareStory'),shareStatus=$('shareStatus');
if(shareStory)shareStory.addEventListener('click',async()=>{track('share',{method:window.navigator&&typeof window.navigator.share==='function'?'native':'link',content_type:'interactive_article',item_id:'ai_football_coach'});const shareData={title:document.title,text:'눈 앞의 기록, 눈 안의 열망',url:window.location?window.location.href:''};shareStatus.textContent='';try{if(window.navigator&&typeof window.navigator.share==='function'){await window.navigator.share(shareData);return;}if(window.navigator&&window.navigator.clipboard&&typeof window.navigator.clipboard.writeText==='function'){await window.navigator.clipboard.writeText(shareData.url);shareStatus.textContent='링크를 복사했습니다.';return;}shareStatus.textContent='주소창의 링크를 복사해 주세요.';}catch(error){if(error&&error.name==='AbortError')return;shareStatus.textContent='공유하지 못했습니다. 다시 시도해 주세요.';}});
const storyTrack=document.querySelector('.vns-carousel-track'),storyPrev=document.querySelector('.vns-prev'),storyNext=document.querySelector('.vns-next');
if(storyTrack&&storyPrev&&storyNext){const syncStoryButtons=()=>{const left=Number(storyTrack.scrollLeft)||0,width=Number(storyTrack.clientWidth)||0,total=Number(storyTrack.scrollWidth)||0;storyPrev.disabled=left<=4;storyNext.disabled=total>width?left+width>=total-4:false;};const moveStories=direction=>{const width=Number(storyTrack.clientWidth)||320;if(typeof storyTrack.scrollBy==='function')storyTrack.scrollBy({left:direction*Math.max(280,width*.82),behavior:reduced?'auto':'smooth'});track('more_story_navigate',{direction:direction<0?'previous':'next'});};storyPrev.addEventListener('click',()=>moveStories(-1));storyNext.addEventListener('click',()=>moveStories(1));storyTrack.addEventListener('scroll',syncStoryButtons,{passive:true});window.addEventListener('resize',syncStoryButtons);syncStoryButtons();}
})();
